chat/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path
urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.AccountRegistration.as_view(), name="signup"),
    path("login/", views.Login, name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),

    path("home/", views.PostListView.as_view(), name="home"), 
    path("my_prof/", views.MyPostListView.as_view(), name="my_prof"),
    path("post/", views.PostCreateView.as_view(), name="post"),
    path("tos/", views.tos, name="tos"),
    path("forgotpass/", views.forgotpass, name="forgotpass"),
    path("favlist/", views.FavListView.as_view(), name="favlist"),
    path("changelog/", views.changelog, name="changelog"),

    path("chat/", views.chat, name="chat"),
    path("chat/<str:room_name>/", views.room, name="room"),
    


    path("post/<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("post/<int:pk>/comment/", views.CommentCreateView.as_view(), name="comment"),
    path("post/<int:pk>/delete/", views.PostDeleteView.as_view(), name="delete"),
    path("post/<int:pk>/fav/", views.FavView.as_view(), name="fav"),
    path("post/<int:pk>/edit/", views.PostEditView.as_view(), name="edit"),
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("chat.urls")),
    path('admin/', admin.site.urls),
]

chat/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    author = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    sex = models.CharField(max_length=10)
    looks = models.CharField(max_length=10)
    type = models.CharField(max_length=10)
    state = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    fav_num = models.IntegerField(default=0)
    comment_num = models.IntegerField(default=0)
    #img = models.ImageField(blank=True, null=True, upload_to='post-image/')
    img =models.TextField(blank=True, null=True)
    pv = models.IntegerField(default=0)
    alt_text = models.CharField(max_length=30, blank=True, null=True)
    def __str__(self):
        return self.title
    def post(self):
        self.created_at = timezone.now()  

class Comment(models.Model):
    post_comment_id = models.IntegerField(default=1)
    comment = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    username = models.CharField(max_length=24)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.text[:20]
    def post(self):
        self.created_at = timezone.now()
#自分がお気に入りした投稿を保存するモデル
class FavoriteList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    def __str__(self):
        return self.post.title

chat/forms.py
from django import forms
from .models import Comment, Post
from django.contrib.auth.models import User
class AccountForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','email',"password")
class CommentForm(forms.ModelForm):
    class Meta:
        #labelを変更
        labels = {
            'text': '',
        }
        model = Comment
        fields = ('text',)

chat/views.py
from django.shortcuts import render
from chat.models import Post, Comment, FavoriteList
from .forms import AccountForm, CommentForm
from django.views.generic import View, TemplateView, ListView,CreateView, DetailView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import time
import base64

#投稿の一覧を表示するビュー
class PostListView(ListView):
    template_name = 'chat/home.html'
    model = Post
    def get_queryset(self):
        if ("order" in self.request.GET):
            if self.request.GET["order"] == "popular":
                return Post.objects.order_by("-fav_num")
            elif self.request.GET["order"] == "new":
                return Post.objects.order_by("-created_at")
            elif self.request.GET["order"] == "veiled":
                return Post.objects.order_by("fav_num")
            elif self.request.GET["order"] == "old":
                return Post.objects.order_by("created_at")
            elif self.request.GET["order"] == "pv":
                return Post.objects.order_by("-pv")
            else:
                return Post.objects.order_by("-created_at")
        return Post.objects.order_by("-created_at")

#お気に入り一覧を表示するビュー
class FavListView(ListView):
    template_name = 'chat/home.html'
    model = Post
    def get_queryset(self):
        fav_list = FavoriteList.objects.filter(user_id=self.request.user.id)
        fav_post = []
        for fav in fav_list:
            fav_post.append(Post.objects.get(pk=fav.post_id))
        return fav_post

#投稿の作成を行うビュー
#authorにアカウントの名前を入れる
#imgが空の場合はNoneを入れ
class PostCreateView(CreateView):
    template_name = 'chat/post.html'
    model = Post
    fields = ('title','sex','looks','type','state','content','img','alt_text')
    def form_valid(self, form):
        form.instance.author = self.request.user
        if self.request.FILES == {}:
            form.instance.img = None
        else:
            form.instance.img = base64.b64encode(self.request.FILES['img'].read()).decode('utf-8')
        return super().form_valid(form)
    #homeにリダイレクト
    success_url = '/home/'

#投稿の詳細を表示するビュー
#PVを1増やす
class PostDetailView(DetailView):
    template_name = "chat/detail.html"
    model = Post
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = Post.objects.get(pk=self.kwargs['pk'])
        if post.author != self.request.user.username:
            post.pv += 1
            post.save()
        context["comment_form"] = CommentForm()
        context["favorite"] = FavoriteList.objects.filter(user_id=self.request.user.id, post_id=self.kwargs['pk'])
        return context

#コメントを作成するビュー
class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    def form_valid(self, form):
        post = Post.objects.get(pk=self.kwargs['pk'])
        #リダイレクト時､PVが増えてしまうので-1
        if post.author != self.request.user.username:
            post.pv -= 1
        post.comment_num += 1
        post.save()
        #post_comment_idにcomment_numを入れる
        form.instance.post_comment_id = post.comment_num
        #comment_idに投稿のidを入れる
        form.instance.comment_id = self.kwargs['pk']
        #usernameにアカウントの名前を入れる 
        form.instance.username = self.request.user
        #textにコメントの内容を入れる
        form.instance.text = form.cleaned_data['text']
        #保存
        form.save()
        return HttpResponseRedirect(reverse('detail', kwargs={'pk': self.kwargs['pk']}))

#自分の投稿を削除するビュー
class PostDeleteView(View):
    def get(self, request, *args, **kwargs):
        #投稿者とログインユーザーが一致しているか確認
        
        post = Post.objects.get(pk=self.kwargs['pk'])
        if post.author == self.request.user.username or self.request.user.is_superuser:
            post.delete()
            return HttpResponseRedirect(reverse('home'))
        else:
            return HttpResponseRedirect(reverse('detail'))

#自分の投稿一覧を表示するビュー
class MyPostListView(ListView):
    template_name = 'chat/home.html'
    model = Post
    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)

#自分の投稿を編集するビュー
class PostEditView(View):
    def get(self, request, *args, **kwargs):
        #投稿者とログインユーザーが一致しているか確認
        if Post.objects.get(pk=self.kwargs['pk']).author == self.request.user:
            post = Post.objects.get(pk=self.kwargs['pk'])
            return render(request, 'chat/edit.html', {'post':post})
        else:
            return HttpResponseRedirect(reverse('home'))

    def post(self, request, *args, **kwargs):
        #投稿者とログインユーザーが一致しているか確認
        if Post.objects.get(pk=self.kwargs['pk']).author == self.request.user:
            post = Post.objects.get(pk=self.kwargs['pk'])
            post.title = request.POST['title']
            post.content = request.POST['content']
            post.save()
            return HttpResponseRedirect(reverse('detail', kwargs={'pk': self.kwargs['pk']}))
        else:
            return HttpResponseRedirect(reverse('home'))

#お気に入りにした投稿のfav_numを+1する
#Favoritelistに投稿のidを保存する
#既にお気に入りにしていたらfav_numを-1し､Favoritelistから削除する
class FavView(View):
    def get(self, request, *args, **kwargs):
        post = Post.objects.get(pk=self.kwargs['pk'])
        fav = FavoriteList.objects.filter(post_id=self.kwargs['pk'], user_id=self.request.user.id)
        if fav:
            post.fav_num -= 1
            post.save()
            fav.delete()
            return HttpResponseRedirect(reverse('detail', kwargs={'pk': self.kwargs['pk']}))
        else:
            post.fav_num += 1
            post.save()
            fav = FavoriteList()
            fav.post_id = self.kwargs['pk']
            fav.user_id = self.request.user.id
            fav.save()
            return HttpResponseRedirect(reverse('detail', kwargs={'pk': self.kwargs['pk']}))




############################################
############ログイン･ログアウト処理###########
############################################
#ログイン
def Login(request):
    if request.method == 'POST':
        # フォーム入力のユーザーID・パスワード取得
        UserName = request.POST.get('username')
        Pass = request.POST.get('password')

        # Djangoの認証機能
        user = authenticate(username=UserName, password=Pass)

        # ユーザー認証
        if user:
            #ユーザーアクティベート判定
            if user.is_active:
                # ログイン
                login(request, user)
                # ホームページ遷移
                return HttpResponseRedirect(reverse('home'))
            else:
                # アカウント利用不可
                return HttpResponse("アカウントが有効ではありません")
        # ユーザー認証失敗
        else:
            return HttpResponse("ログインIDまたはパスワードが間違っています")
    # GET
    else:
        return render(request, 'chat/login.html')

class  AccountRegistration(TemplateView):

    def __init__(self):
        self.params = {
        "AccountCreate":False,
        "account_form": AccountForm(),
        }

    # Get処理
    def get(self,request):
        self.params["account_form"] = AccountForm()
        self.params["AccountCreate"] = False
        return render(request,"chat/signup.html",context=self.params)

    # Post処理
    def post(self,request):
        self.params["account_form"] = AccountForm(data=request.POST)
        #Email重複していないなら
        if not User.objects.filter(email=request.POST.get("email")).exists():
            #チェックボックスがオンになっているか検証
            if request.POST.get("checkbox") != "checked":
                return HttpResponse("利用規約に同意してください")
            else:
                #パスワードが一致しているか検証
                if request.POST.get("password") != request.POST.get("confirm-password"):
                    return HttpResponse("パスワードが一致しません")
                else:
                # フォーム入力の有効検証
                    if not self.params["account_form"].is_valid():
                        print(self.params["account_form"].errors)
                    else:
                        # アカウント情報をDB保存
                        account = self.params["account_form"].save()
                        # パスワードをハッシュ化
                        account.set_password(account.password)
                        # ハッシュ化パスワード更新
                        account.save()
    
                        # 画像アップロード有無検証
                        #if 'account_image' in request.FILES:
                        #    add_account.account_image = request.FILES['account_image']
                        # アカウント作成情報更新
                        self.params["AccountCreate"] = True
                        # 成功したら自動でログインし､ホームページへ遷移
                        login(request, account)
                        return HttpResponseRedirect(reverse('home'))                        
        else:
            return HttpResponse("このメールアドレスは既に登録されています")
        return render(request,"chat/signup.html",context=self.params)

class Logout(LogoutView):
    template_name = "chat/logout.html"
    next_page = "home"

# simple url define
def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home'))
    else:
        return render(request, "chat/index.html")
def others_prof(request):
    return render(request, "chat/others_prof.html")
def post(request):
    return render(request, "chat/post.html")
def tos(request):
    return render(request, "chat/tos.html")
def forgotpass(request):
    return render(request, "chat/forgotpass.html")
def chat(request):
    return render(request, "chat/chat.html")
def room(request, room_name):
    return render(request, "chat/room.html", {"room_name": room_name})
def signupold(request):
    return render(request, "chat/signup-old.html")
def changelog(request):
    return render(request, "chat/changelog.html")

chat/templates/chat/changeLog.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>変更履歴</title>
</head>

<body>

    <div class="">
        <h2>2023/01/12</h2>
        画像投稿しても反映されないのを修正 ←まだ治ってなかった<br>
        Detailのレイアウトを微調整<br>
        コメントボタンを連打すると複数送信されてしまうのを修正<br>
    </div>
    
    <div>
        <h2>2023/01/13</h2>
        変更履歴表示<br>
        ホーム画面に流れるアナウンスを追加<br>
        画像投稿しても反映されないのを修正<br>
            <ul>
                <li>どうやらRenderの無料プランはGitのリポジトリにはないファイルを定期的に削除しているらしい</li>
                <li>なので画像が一定時間経つと表示されなくなっていた</li>
            </ul>
        ･解決策<br>
            <ul>
                <li>models.pyの画像のfieldをImageFieldからTextFieldに変更</li>
                <li>画像投稿時､base64形式にエンコードしてDBに保存(base64はテキストなので画像ファイル扱いにならない)</li>
                <li>画像表示時､デコードして表示</li>
                で解決しました｡ご参考までに｡
            </ul>
    
    </div>
    
    <div>
        <h2>2023/01/29</h2>
        indexページのアニメーション追加とスマホ対応(画像はまだ)<br>
        ログイン状態のままDEVIANTにアクセスすると自動でホームに移動するように変更<br>
        Signupボタンを設置<br>
        投稿の画像にマウスオーバーすると拡大表示されるように変更<br>
        投稿の削除ボタンのバグを修正<br>
    </div>
    


    
<a href="{% url 'home' %}">Homeに戻る</a>
</body>

</html>

chat/templates/chat/chat.html
<!DOCTYPE html>
{% extends 'chat/header2.html' %}
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}Chat{% endblock title %}</title>
    
</head>
{% block header %}

<body>
   <div class="flex justify-center grid grid-rows-3 text-3xl p-16 m-10 bg-gray-200 rounded-xl shadow-xl">
       <div> 入りたい部屋の名前を入力してください:<br><p class="text-xl">※アルファベットのみで15文字以内</p></div>
       
        <div class="flex justify-center"><input id="room-name-input" type="text" size="15" required class="border-4 text-6xl rounded-xl"></div><br>
        <div class="flex justify-end"><input id="room-name-submit" type="button" value="入室"class="bg-gray-500 hover:bg-gray-400 text-white rounded px-4 py-2"></div>
   </div>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            if (roomName == "") {
                window.location.pathname = '/chat/'
            }
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
{% endblock %}
</html>

chat/templates/chat/index.html
<!DOCTYPE html>
{% extends 'chat/header2.html' %}
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}DEVIANT{% endblock title %}</title>
    {% block script %}
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/scrollreveal"></script>
    <link rel="stylesheet" href="{% static 'css/load.css' %}">
    <script src="https://cdn.tailwindcss.com"></script>
    
    {% endblock %}
</head>
{% block header %}
<body>

    <img src="{% static 'img/index2.jpg' %}" style="background-size: cover; opacity:0.5;position:fixed;z-index:3;">
    <div name="main" class="py-16 md:p-36 md:pr-48 md:text-8xl font-serif">
        
        <div id="title1" class="px-4 text-4xl md:text-8xl">“DEVIANT”</div>

        <br><br><br>

        <div class="flex justify-end text-3xl md:text-6xl "id="title2">
        -キミの世界を広げよう｡-
        </div>

    </div>
    <script>
        ScrollReveal().reveal('#title1', {
            delay: 150,
            reset: false,
            origin: 'left',
            viewFactor: 0.2,
            duration: 1200,
            distance: '70px',
     });

        ScrollReveal().reveal('#title2', {
            delay: 350,
            reset: false,
            origin: 'right',
            viewFactor: 0.2,
            duration: 1200,
            distance: '70px',
     });

    </script>
</body>
{% endblock %}
</html>

chat/templates/chat/others_prof.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Profile</title>
</head>
<body>

    <h1>This is  others Profile</h1>

    <script>
    </script>
</body>
</html>

chat/templates/chat/post.html
<!DOCTYPE html>
{% extends 'chat/header2.html' %}
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}投稿{% endblock %}</title>
{% comment %} 
    {%block script%}
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/loadBlack.css' %}">
    {%endblock%}
     {% endcomment %}
</head>
{% block header %}

<body class="" >
  <img src="{% static 'img/postbg.png' %}" style="width:100%;height:100%;object-fit:cover;position:fixed;z-index:-3;">
{% if request.user.is_authenticated %}
 <!--Postモデルを利用した投稿機能-->
<div name="main" class="p-6 md:p-16">
   <form action="" method="post" enctype="multipart/form-data" class="p-8 bg-gradient-to-r from-indigo-100 via-sky-100 to-blue-100 shadow-xl m-4 border-b-8 border-r-8 border-t border-l border-gray-100 rounded-lg font-mono"><!--投稿完了を表示させたい-->
  {%csrf_token%}
  <div class="m-3">
  
  <div name="上部分" class="grid grid-cols-1 md:grid-cols-2">
      {% comment %} <div name="左"class="">
          <label for="id_image">画像</label>
          <input type="file" name="img" class="w-full" id="img" accept="image/*">
        </div> {% endcomment %}
  
        <div class="max-w-xl">
          <label
              class="flex justify-center w-full h-32 px-4 transition bg-white border-2 border-gray-300 border-dashed rounded-md appearance-none cursor-pointer hover:border-gray-400 focus:outline-none text-2xl shadow-md" id="dropArea">
              <span class="flex items-center space-x-2">
                  <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-gray-600" fill="none" viewBox="0 0 24 24"
                      stroke="currentColor" stroke-width="2">
                      <path stroke-linecap="round" stroke-linejoin="round"
                          d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                  </svg>
                  <span class="font-medium text-gray-600" id="UploadField">
                      画像をドロップ､または
                      <span class="text-blue-600 hover:underline">選択</span>
                  </span>
              </span>
              <input type="file" name="img" class="hidden" id="img" accept="image/*" onclick="fileSelected()">
          </label>
          <div class="m-2 text-2xl">
            <label for="title">撮影詳細</label>
            <input type="title" name="alt_text" class="w-full resize-none text-base border border-gray-300" >
            <div class="mt-2 m-2 text-sm">
              <p>※35文字以内</p>
            </div>
          </div>
      </div>
  
    <div name="右" class="container md:mx-16">
  
  
          <div class="m-2 text-lg md:text-3xl">
            <label for="title">名前</label>
            <input type="title" name="title" class="" required id="title">
          </div>
  
          <div class="m-2 text-lg md:text-3xl">
            <label for="id_sex">性別</label>
            <select name="sex" class="" required >
              <option value="" disabled selected>--- 性別を選択 ---</option>
              <option value="男性">男</option>
              <option value="女性">女</option>
              <option value="その他">その他</option>
            </select>
          </div>
          
          <div class="m-2 text-lg md:text-3xl">
            <label for="looks">分類</label>
            <select name="looks" class="" required>
                <option value="" disabled selected>--- 分類を選択 ---</option>
                <option value="COOL">COOL</option>
                <option value="CUTE">CUTE</option>
                <option value="BEAUTIFUL">BEAUTIFUL</option>
                <option value="その他">その他</option>
            </select>
        </div>
  
          <div class="m-2 text-lg md:text-3xl">
              <label for="type">種族</label>
              <select name="type" class="" required>
                  <option value="" disabled selected>--- 種族を選択 ---</option>
                  <option value="人間">人間</option>
                  <option value="人外">人外</option>
                  <option value="その他">その他</option>
              </select>
          </div>
          
          <div class="m-2 text-lg md:text-3xl">
              <label for="state" class="">状態</label>
              <select name="state" class="" required>
                <option value="" disabled selected>--- 状態を選択 ---</option>
                  <option value="処分済">処分済</option>
                  <option value="捕獲済">捕獲済</option>
                  <option value="監視中">監視中</option>
                  <option value="その他">その他</option>
              </select>
          </div>
    </div name="右">
  
  </div name="上部分">
  
      <div class="">
        <p class="mt-5 text-3xl">報告内容</p>
        <label for="id_content"></label>
        <textarea name="content" class="mt-2 w-full resize-none text-base rounded-2xl border border-gray-300 p-4" required id="content" rows="10" ></textarea>
      </div>
  
      
      <div class="" style="text-align:right;"><button type="submit" class="border-2 border-gray-400 rounded pr-2 pl-2">報告</button></div>
  </div>
  
    </form>
</div name="main">




{% else %}<br><br>
    <p class="m-4 text-2xl md:m-16 md:text-4xl">投稿するには<a href={% url 'login' %}><strong>ログイン</strong></a>してください。</p>
{% endif %}


 <script>
  ////////////////////////////////////////////////
// ドラッグ&ドロップエリアの取得
////////////////////////////////////////////////
 // ドラッグ&ドロップエリアの取得
var fileArea = document.getElementById('dropArea');

// input[type=file]の取得
var fileInput = document.getElementById('img');

// ドラッグオーバー時の処理
fileArea.addEventListener('dragover', function(e){
    e.preventDefault();
    fileArea.classList.add('dragover');
});

// ドラッグアウト時の処理
fileArea.addEventListener('dragleave', function(e){
    e.preventDefault();
    fileArea.classList.remove('dragover');
});

// ドロップ時の処理
fileArea.addEventListener('drop', function(e){
    e.preventDefault();
    fileArea.classList.remove('dragover');

    // ドロップしたファイルの取得
    var files = e.dataTransfer.files;

    // 取得したファイルをinput[type=file]へ
    fileInput.files = files;
    
    if(typeof files[0] !== 'undefined') {
        //ファイルが正常に受け取れた際の処理
        //id=UploadFieldにファイル名を表示
        var fileName = document.getElementById('UploadField');
        fileName.innerHTML = files[0].name;
        //枠に収まるようにプレビュー表示
        var area = document.getElementById('dropArea');
        var img = document.createElement('img');
        img.src = window.URL.createObjectURL(files[0]);
        img.style.width = "100";
        img.style.height = "100";
        img.className = "m-2";

        area.appendChild(img);
    } else {
        //ファイルが受け取れなかった際の処理
    }
});

// input[type=file]に変更があれば実行
fileInput.addEventListener('change', function(e){
    var file = e.target.files[0];
    
    if(typeof e.target.files[0] !== 'undefined') {
        // ファイルが正常に受け取れた際の処理
        var fileName = document.getElementById('UploadField');
        fileName.innerHTML = files[0].name;
        //枠に収まるようにプレビュー表示
        var area = document.getElementById('dropArea');
        var img = document.createElement('img');
        img.src = window.URL.createObjectURL(files[0]);
        img.style.width = "100";
        img.style.height = "100";
        img.className = "m-2";
        
        area.appendChild(img);
    } else {
      fileName.innerHTML = "INPUT ERROR!";
    }
}, false);
//普通にファイルを選択した場合の処理
$("#img").change(function(){
    var file = $(this).prop('files')[0];
    if(typeof file !== 'undefined') {
        // ファイルが正常に受け取れた際の処理
        var fileName = document.getElementById('UploadField');
        fileName.innerHTML = file.name;
        //枠に収まるようにプレビュー表示
        var area = document.getElementById('dropArea');
        var img = document.createElement('img');
        img.src = window.URL.createObjectURL(file);
        img.style.width = "100";
        img.style.height = "100";
        img.className = "m-2";
        area.appendChild(img);
    } else {
        // ファイルが受け取れなかった際の処理
        fileName.innerHTML = "INPUT ERROR!";
      }
});



/*
function fileSelected() {
    var file = document.getElementById('img').files[0];
    if (file) {
        var fileSize = 0;
        if (file.size > 1024 * 1024)
            fileSize = (Math.round(file.size * 100 / (1024 * 1024)) / 100).toString() + 'MB';
        else
            fileSize = (Math.round(file.size * 100 / 1024) / 100).toString() + 'KB';
        document.getElementById('UploadField').innerHTML = 'ファイル名: ' + file.name + ', ファイルサイズ: ' + fileSize;
    }
}*/


/////////////////////////////////////////////////////////
////////////////////ANIMATION///////////////////////////
/////////////////////////////////////////////////////////
$(function(){
	var cover = $('.cover');
  var loader = $('.loader');
  var loaderBox = $('.loaderBox');

	//ページの読み込みが完了したらアニメーションを非表示
	$(window).on('load',function(){
		cover.delay(200).fadeOut(200);
	});

	//ページの読み込みが完了してなくても3秒後にアニメーションを非表示にする
	setTimeout(function(){
		cover.fadeOut();
	},3000);
//////////////////////LOADER///////////////////////////
  $(window).on('load',function(){
		loader.delay(300).fadeOut(300);
    loaderBox.delay(300).fadeOut(300);
	});

	setTimeout(function(){
		loader.fadeOut();
    loaderBox.fadeOut();
	},3000);
  });


    </script>

</body>
{% endblock %}
</html>

chat/templates/chat/tos.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <title>Terms of Service</title>
</head>
<body>

    <h1>よいこのためのりようきやく</h1><br>
    <p>特にないけど､まあ節度とか節度とかは守ってね</p>
    <br><br>
<a href="{% url 'home' %}">Homeに戻る</a>
    <script>
    </script>
</body>
</html>